### ISSUE TITLE
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

### ISSUE THREAD

**Issue by guillem-palau-salva** [AnKing-Memberships/ankiweb-placeholder#10]
## Which add-on is this about?
exam notifier
https://app.kajabi.com/admin/comments/2155682594

#### Problem description

Just got anki, trying it for the first time as a veterinary student. I keep getting this error.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 

```
2.1.54
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.5.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-08-24 20:17:51
Add-ons possibly involved: ⁨Exam Notifier⁩

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 42, in cmd
File "aqt.webview", line 149, in _onCmd
File "aqt.webview", line 618, in _onBridgeCmd
File "aqt.hooks_gen", line 4358, in __call__
File "/Users/test/Library/Application Support/Anki2/addons21/exam_notifier/deck_options.py", line 150, in on_webview_did_receive_js_message
DeckConf(self._main_window, deck_legacy)
File "aqt.deckconf", line 40, in __init__
File "aqt.hooks_gen", line 1604, in __call__
File "/Users/test/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 109, in on_deck_config_gui_loaded
deck_config_tab = self._factory(parent=deck_conf_dialog)
File "/Users/test/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 63, in __init__
self._qdatetime_from_epoch(unix_time_now)
File "/Users/test/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 89, in _qdatetime_from_epoch
qdatetime.setTime_t(unix_epoch)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'
```

**Comment by AnKingMed** [comment]
Thanks. You can tell the user to use Qt5 for now
