### ISSUE TITLE
pdf EXPORTer

### ISSUE THREAD

**Issue by bguati** [AnKing-Memberships/ankiweb-placeholder#120]
## Which add-on is this about?
PDF exporter

#### Problem description

the add-on that it’s not showing the content inside “buttons”/fields , also when I try to "save template" the crash message shows:
O Anki encontrou um problema. Por favor, siga os passos de solução de problemas.

Extensões possivelmente envolvidas: ⁨PDF Exporter⁩
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*⁨24.06.3 (d678e393)⁩

```
2.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/brunaguatimosim/Library/Application Support/Anki2/addons21/1442112168/clayout.py", line 47, in <lambda>
    lambda: _save_current_template_as_export_template(clayout)
  File "/Users/brunaguatimosim/Library/Application Support/Anki2/addons21/1442112168/clayout.py", line 94, in _save_current_template_as_export_template
    get_export_template_paths(clayout.model["name"], ord)[0].write_text(
  File "pathlib", line 1286, in write_text
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 106: ordinal not in range(128)

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Table ['1237621971', 2023-06-18T08:37, 'None', mod]
Advanced Review Bottom Bar ['1136455830', 2024-08-22T08:04, 'None', '']
Anki Simulator ['817108664', 2023-11-06T14:26, 'None', '']
AnkiHub ['1322529746', 2024-10-21T14:10, 'None', '']
Basic Printing Support ['1025789669', 2023-10-18T23:57, 'None', '']
BetterSearch ['1052724801', 2024-03-06T13:25, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T12:06, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-01-03T04:19, '6.18', mod]
Enhanced Cloze for Anki 21 ['1990296174', 2023-09-10T15:48, 'None', '']
Export Deck to HTML and Print to PDF ['266464821', 2022-05-25T02:23, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T13:58, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-11-03T22:56, 'None', '']
Filtered deck from browser selection - study review cards in browser order ['127393092', 2023-03-19T15:02, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-21T16:17, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T04:15, 'None', '']
Opening the same window multiple time ['354407385', 2023-11-04T22:59, 'None', '']
PDF Exporter ['1442112168', 2023-03-20T20:53, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T02:42, 'None', '']
True Retention ['613684242', 2017-11-19T18:43, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T11:12, 'None', mod]

===IDs of active AnkiWeb add-ons===
1025789669 1052724801 1135507717 1136455830 1237621971 127393092 1322529746 1374772155 1442112168 1771074083 1990296174 2040501954 225180905 266464821 354407385 385888438 594329229 613684242 759844606 805891399 817108664

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by AnKingMed** [comment]
@abdnh can you look into this?

**Comment by abdnh** [comment]
Pushed a fix.

**Comment by bguati** [comment]
how can I download the fixed version?

**Comment by AnKingMed** [comment]
It's on the VIP dashboard now
