### ISSUE TITLE
Uworld QID

### ISSUE THREAD

**Issue by Joshausha** [AnKing-Memberships/ankiweb-placeholder#2]
When attempting to use the Uworld QID 1.3 on the new version of anki I receive this error message:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.52 (ab1c2395) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-05-23 16:07:49
Add-ons possibly involved: ⁨uworld_qid_to_anki_search⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 402, in <lambda>
    action.triggered.connect(lambda _, b=self: import_transform_and_search(b))
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 380, in import_transform_and_search
    user_text, ret = getText("Copy the comma separated list of strings")
  File "aqt.utils", line 363, in getText
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

Caught exception:
Traceback (most recent call last):
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 402, in <lambda>
    action.triggered.connect(lambda _, b=self: import_transform_and_search(b))
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 380, in import_transform_and_search
    user_text, ret = getText("Copy the comma separated list of strings")
  File "aqt.utils", line 363, in getText
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

Caught exception:
Traceback (most recent call last):
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 402, in <lambda>
    action.triggered.connect(lambda _, b=self: import_transform_and_search(b))
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 380, in import_transform_and_search
    user_text, ret = getText("Copy the comma separated list of strings")
  File "aqt.utils", line 363, in getText
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

Caught exception:
Traceback (most recent call last):
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 402, in <lambda>
    action.triggered.connect(lambda _, b=self: import_transform_and_search(b))
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 380, in import_transform_and_search
    user_text, ret = getText("Copy the comma separated list of strings")
  File "aqt.utils", line 363, in getText
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

**Comment by AnKingMed** [comment]
I just tested this and mine is working. It looks like you might have an older version. Did you download the latest version that was shared just a few days ago?

**Comment by Joshausha** [comment]
Re-downloaded and reinstalled both Anki and the Uworld QID to make sure I have the most up to date versions. Still getting the same error message. When I press "Import" no dialog box appears and when I press "Export" I receive this error as well.
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.52 (ab1c2395) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-05-23 18:11:34
Add-ons possibly involved: ⁨uworld_qid_to_anki_search⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 361, in export_45_on_success
    browser.form.searchEdit.lineEdit().setText(search_string)
AttributeError: form

**Comment by AnKingMed** [comment]
Can you find and delete this add-on in your repo: ⁨uworld_qid_to_anki_search⁩

**Comment by Joshausha** [comment]
Should I delete and then reinstall the addon or just delete it?

**Comment by AnKingMed** [comment]
The problem is there's two add-ons.  One with a folder named ⁨uworld_qid_to_anki_search⁩, one with a number.  It was supposed to toggle off the old one (⁨uworld_qid_to_anki_search⁩) but it looks like that part of our code didn't work

**Comment by Joshausha** [comment]
I don't think that's the issue, I deleted the add on from the anki "add on" menu and searched in the repo section on my computer for the add on and there's no "uworld_qid_to_anki_search⁩" add on. So I reinstalled version 1.3 of the Uworld QID add on and am having the same issue. The add on should be associated with a numbered file and not with a named file in the repo section correct?

**Comment by Joshausha** [comment]
Thanks!

**Comment by ijgnd** [comment]
thanks for your bug report - including the whole error message is really useful.

Could you try out the attached modified version? This is an ankiaddon file but github doesn't allow to upload those. So I added a known extension ".zip". After downloading could you remove it, i.e. change the filename from `uworld_qid_to_anki_search_v1.6.ankiaddon.zip` to `uworld_qid_to_anki_search_v1.6.ankiaddon`. Then install it as usual.

At least [this bug](https://github.com/AnKing-Memberships/ankiweb-placeholder/issues/2#issuecomment-1134810980) and probably also the other one should be fixed.

This week I have hardly any time so I only did a very cursory test on MacOS 12.3.1 where I didn't have an Anking deck so I couldn't test the export. At least on the import I didn't immediatly run into bugs.

[uworld_qid_to_anki_search_v1.6.ankiaddon.zip](https://github.com/AnKing-Memberships/ankiweb-placeholder/files/8757283/uworld_qid_to_anki_search_v1.6.ankiaddon.zip)

**Comment by ijgnd** [comment]
general remarks (copied and pasted from other threads):

for the future: For a perfect bug report: Say if the error occurs after you have disabled all other add-ons and have restarted anki. A surprising number of problems is due to add-on conflicts ... (thought not this problem here ...)

&nbsp;

If you like technical details: When trying out a new version of an add-on and find out if this new add-on works on its own: Instead of disabling all other add-ons I usually use a different approach. I close Anki, then I rename my add-on folder (which is named `addons21` to something like `addons21_all_mine`) in my profile so that Anki doesn't find it and on the next restart it creates a new empty addons21 folder. Then I install the new add-on, restart anki, and then try out the new add-on. When I'm done I delete the recently created `addons21` folder and rename `addons21_all_mine` back to `addons21`. This way I don't delete/modify anything in my real add-on folder by accident and I don't need to remember which add-ons I originally had disabled ... For the folder location see: https://docs.ankiweb.net/files.html#file-locations

**Comment by Joshausha** [comment]
Thanks for getting back to me so quickly. I installed the new add-on you sent which didn't work. I then renamed my add-on folder like you suggested to check for conflicts. With only the 1.6 version of the Uworld QID add-on installed I received this error:


Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.52 (ab1c2395) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-05-23 18:11:34
Add-ons possibly involved: ⁨uworld_qid_to_anki_search⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 402, in <lambda>
    action.triggered.connect(lambda _, b=self: import_transform_and_search(b))
  File "/Users/*/Library/Application Support/Anki2/addons21/607963104/__init__.py", line 380, in import_transform_and_search
    user_text, ret = getText("Copy the comma separated list of strings")
  File "aqt.utils", line 363, in getText
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

**Comment by Joshausha** [comment]
Works perfectly now! You're fantastic and don't forget it! Thanks for the help!
